before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
    binary: "{{.ProjectName}}{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
archives:
  - format_overrides:
    - goos: windows
      format: zip
    name_template: "{{.ProjectName}}{{.Version}}.{{.Os}}-{{.Arch}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
